import { type AdminProduct, type ProductFilters } from "./types"

const now = new Date()
const daysAgo = (d: number) => {
  const date = new Date(now)
  date.setDate(date.getDate() - d)
  return date.toISOString().split("T")[0]
}

const categoryLabel = (cat: string) => {
  const labels: Record<string, string> = {
    "full-face": "Full Face",
    modular: "Modular",
    "open-face": "Open Face",
    "3/4": "3/4",
  }
  return labels[cat] ?? cat
}

function generateDescription(product: { name: string; brand: string; category: string; price: number }): string {
  return `The ${product.name} by ${product.brand} is a premium ${categoryLabel(product.category).toLowerCase()} motorcycle helmet designed for riders who demand the best in protection, comfort, and style. Featuring advanced shell construction, superior ventilation, and a lightweight design, this helmet delivers exceptional performance on every ride. Priced at $${product.price.toFixed(2)}, it offers outstanding value for its class.`
}

const rawProducts: AdminProduct[] = [
  {
    id: "1",
    name: "Arai RX-7X Evo",
    sku: "HELM-0001",
    brand: "Arai",
    category: "full-face",
    price: 899.99,
    originalPrice: 999.99,
    stock: 42,
    status: "active",
    rating: 4.8,
    reviewCount: 124,
    createdAt: daysAgo(12),
    image: "/placeholder-helmet.svg",
  },
  {
    id: "2",
    name: "Shoei X-Fifteen",
    sku: "HELM-0002",
    brand: "Shoei",
    category: "full-face",
    price: 799.99,
    originalPrice: 899.99,
    stock: 28,
    status: "active",
    rating: 4.7,
    reviewCount: 98,
    createdAt: daysAgo(15),
    image: "/placeholder-helmet.svg",
  },
  {
    id: "3",
    name: "AGV Pista GP RR",
    sku: "HELM-0003",
    brand: "AGV",
    category: "full-face",
    price: 1499.99,
    stock: 12,
    status: "active",
    rating: 4.9,
    reviewCount: 67,
    createdAt: daysAgo(20),
    image: "/placeholder-helmet.svg",
  },
  {
    id: "4",
    name: "Scorpion EXO-R1 Air",
    sku: "HELM-0004",
    brand: "Scorpion",
    category: "full-face",
    price: 549.99,
    originalPrice: 629.99,
    stock: 56,
    status: "active",
    rating: 4.5,
    reviewCount: 203,
    createdAt: daysAgo(5),
    image: "/placeholder-helmet.svg",
  },
  {
    id: "5",
    name: "HJC RPHA 91",
    sku: "HELM-0005",
    brand: "HJC",
    category: "modular",
    price: 499.99,
    stock: 35,
    status: "active",
    rating: 4.4,
    reviewCount: 156,
    createdAt: daysAgo(8),
    image: "/placeholder-helmet.svg",
  },
  {
    id: "6",
    name: "Bell Race Star DLX",
    sku: "HELM-0006",
    brand: "Bell",
    category: "full-face",
    price: 699.99,
    originalPrice: 799.99,
    stock: 0,
    status: "draft",
    rating: 4.6,
    reviewCount: 89,
    createdAt: daysAgo(30),
    image: "/placeholder-helmet.svg",
  },
  {
    id: "7",
    name: "LS2 Thunder Carbon",
    sku: "HELM-0007",
    brand: "LS2",
    category: "full-face",
    price: 399.99,
    stock: 78,
    status: "active",
    rating: 4.3,
    reviewCount: 178,
    createdAt: daysAgo(3),
    image: "/placeholder-helmet.svg",
  },
  {
    id: "8",
    name: "KYT NZ Race",
    sku: "HELM-0008",
    brand: "KYT",
    category: "full-face",
    price: 299.99,
    originalPrice: 379.99,
    stock: 64,
    status: "active",
    rating: 4.2,
    reviewCount: 245,
    createdAt: daysAgo(10),
    image: "/placeholder-helmet.svg",
  },
  {
    id: "9",
    name: "Arai XD-4 Adventure",
    sku: "HELM-0009",
    brand: "Arai",
    category: "modular",
    price: 749.99,
    stock: 18,
    status: "active",
    rating: 4.7,
    reviewCount: 87,
    createdAt: daysAgo(22),
    image: "/placeholder-helmet.svg",
  },
  {
    id: "10",
    name: "Shoei Neotec 3",
    sku: "HELM-0010",
    brand: "Shoei",
    category: "modular",
    price: 649.99,
    originalPrice: 729.99,
    stock: 23,
    status: "active",
    rating: 4.6,
    reviewCount: 134,
    createdAt: daysAgo(14),
    image: "/placeholder-helmet.svg",
  },
  {
    id: "11",
    name: "AGV K6 S",
    sku: "HELM-0011",
    brand: "AGV",
    category: "full-face",
    price: 549.99,
    stock: 47,
    status: "active",
    rating: 4.5,
    reviewCount: 192,
    createdAt: daysAgo(7),
    image: "/placeholder-helmet.svg",
  },
  {
    id: "12",
    name: "HJC i100",
    sku: "HELM-0012",
    brand: "HJC",
    category: "modular",
    price: 329.99,
    originalPrice: 399.99,
    stock: 31,
    status: "draft",
    rating: 4.1,
    reviewCount: 267,
    createdAt: daysAgo(45),
    image: "/placeholder-helmet.svg",
  },
  {
    id: "13",
    name: "Bell Qualifier DLX",
    sku: "HELM-0013",
    brand: "Bell",
    category: "full-face",
    price: 219.99,
    stock: 92,
    status: "active",
    rating: 4.0,
    reviewCount: 412,
    createdAt: daysAgo(2),
    image: "/placeholder-helmet.svg",
  },
  {
    id: "14",
    name: "Scorpion EXO-491",
    sku: "HELM-0014",
    brand: "Scorpion",
    category: "modular",
    price: 279.99,
    originalPrice: 349.99,
    stock: 0,
    status: "archived",
    rating: 4.2,
    reviewCount: 189,
    createdAt: daysAgo(90),
    image: "/placeholder-helmet.svg",
  },
  {
    id: "15",
    name: "LS2 Flex Retro",
    sku: "HELM-0015",
    brand: "LS2",
    category: "3/4",
    price: 189.99,
    stock: 53,
    status: "active",
    rating: 4.0,
    reviewCount: 156,
    createdAt: daysAgo(18),
    image: "/placeholder-helmet.svg",
  },
  {
    id: "16",
    name: "KYT Sky Fighter",
    sku: "HELM-0016",
    brand: "KYT",
    category: "full-face",
    price: 249.99,
    originalPrice: 299.99,
    stock: 41,
    status: "active",
    rating: 4.1,
    reviewCount: 203,
    createdAt: daysAgo(11),
    image: "/placeholder-helmet.svg",
  },
  {
    id: "17",
    name: "Shoei J-Cruise 3",
    sku: "HELM-0017",
    brand: "Shoei",
    category: "open-face",
    price: 549.99,
    stock: 19,
    status: "active",
    rating: 4.5,
    reviewCount: 78,
    createdAt: daysAgo(25),
    image: "/placeholder-helmet.svg",
  },
  {
    id: "18",
    name: "Arai Ram-X",
    sku: "HELM-0018",
    brand: "Arai",
    category: "open-face",
    price: 649.99,
    stock: 14,
    status: "draft",
    rating: 4.6,
    reviewCount: 92,
    createdAt: daysAgo(60),
    image: "/placeholder-helmet.svg",
  },
  {
    id: "19",
    name: "HJC V10",
    sku: "HELM-0019",
    brand: "HJC",
    category: "full-face",
    price: 449.99,
    stock: 37,
    status: "active",
    rating: 4.3,
    reviewCount: 112,
    createdAt: daysAgo(9),
    image: "/placeholder-helmet.svg",
  },
  {
    id: "20",
    name: "Bell Eliminator",
    sku: "HELM-0020",
    brand: "Bell",
    category: "full-face",
    price: 379.99,
    originalPrice: 449.99,
    stock: 25,
    status: "active",
    rating: 4.4,
    reviewCount: 145,
    createdAt: daysAgo(16),
    image: "/placeholder-helmet.svg",
  },
  {
    id: "21",
    name: "AGV X3000",
    sku: "HELM-0021",
    brand: "AGV",
    category: "open-face",
    price: 329.99,
    stock: 33,
    status: "active",
    rating: 4.2,
    reviewCount: 167,
    createdAt: daysAgo(13),
    image: "/placeholder-helmet.svg",
  },
  {
    id: "22",
    name: "Scorpion Covert R",
    sku: "HELM-0022",
    brand: "Scorpion",
    category: "open-face",
    price: 199.99,
    stock: 61,
    status: "active",
    rating: 3.9,
    reviewCount: 234,
    createdAt: daysAgo(6),
    image: "/placeholder-helmet.svg",
  },
  {
    id: "23",
    name: "LS2 Pioneer",
    sku: "HELM-0023",
    brand: "LS2",
    category: "full-face",
    price: 149.99,
    originalPrice: 179.99,
    stock: 85,
    status: "active",
    rating: 3.8,
    reviewCount: 389,
    createdAt: daysAgo(4),
    image: "/placeholder-helmet.svg",
  },
  {
    id: "24",
    name: "KYT Fly Style",
    sku: "HELM-0024",
    brand: "KYT",
    category: "3/4",
    price: 129.99,
    stock: 0,
    status: "archived",
    rating: 3.7,
    reviewCount: 312,
    createdAt: daysAgo(120),
    image: "/placeholder-helmet.svg",
  },
]

export const adminProducts: AdminProduct[] = rawProducts.map((p) => ({
  ...p,
  description: generateDescription(p),
}))

export function getFilteredProducts(
  products: AdminProduct[],
  filters: ProductFilters,
): AdminProduct[] {
  return products.filter((product) => {
    if (filters.search) {
      const q = filters.search.toLowerCase()
      const match =
        product.name.toLowerCase().includes(q) ||
        product.sku.toLowerCase().includes(q) ||
        product.brand.toLowerCase().includes(q)
      if (!match) return false
    }

    if (filters.category && product.category !== filters.category) {
      return false
    }

    if (filters.brand) {
      const brandSlug = product.brand.toLowerCase()
      if (brandSlug !== filters.brand) return false
    }

    if (filters.status && product.status !== filters.status) {
      return false
    }

    return true
  })
}
